# action.yml
name: 'KICS Github Action'
description: 'Run KICS scan against IaC projects'
inputs:
  path:
    description: 'path to file or directory to scan'
    required: true
  output_path:
    description: 'file path to store result in json format'
    required: false
  payload_path:
    description: 'file path to store source internal representation in JSON format'
    required: false
  queries:
    description: 'path to directory with queries (default "./assets/queries")'
    required: false
  verbose:
    description: 'verbose scan'
outputs:
  results:
    description: 'the result of KICS scan'
branding:
  icon: 'shield'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.output_path }}
    - ${{ inputs.payload_path }}
    - ${{ inputs.queries }}
    - ${{ inputs.versbose }}
